### ISSUE TITLE
Meeting regarding Initiation of Project - 13-03-2018

### ISSUE THREAD

**Issue by gauravjain99** [CodeDocsJECRC/CodeDocs-App#1]
This meeting will be for discussion of initiation of CodeDocs Android App proposed by Abhimanyu

## Time
TBD

## Agenda
- Content Structure
- UI
- Features
- Work to be divided

## Invited Members
- @CodeDocsJECRC/android 
- Abhimanyu - [**@Abhimanyu121**](https://github.com/Abhimanyu121)
## Links
Zoom link - *will be shared before 5 minutes*

Google Docs Link - *link*

**Comment by prateekvijayvergiya** [comment]
Link for meeting
https://zoom.us/j/462499758

**Comment by prateekvijayvergiya** [comment]
Join again - https://zoom.us/j/167897684
